#!/usr/bin/perl -w
# See License.txt for copyright and terms of use

use warnings;
use strict;
use FindBin;
use lib "${FindBin::RealBin}/lib/build-interceptor";
use BuildInterceptor::Version;

my $print_newline = 1;
my $print_protocol_version = 0;

if ($ARGV[0] && $ARGV[0] eq '-n') {
    $print_newline = 0;
    shift @ARGV;
}

if ($ARGV[0] && $ARGV[0] eq '-p') {
    $print_protocol_version = 1;
    shift @ARGV;
}

if ($print_protocol_version) {
    print $BuildInterceptor::Version::BUILD_INTERCEPTOR_PROTOCOL_VERSION;
} else {
    print $BuildInterceptor::Version::BUILD_INTERCEPTOR_VERSION;
}

if ($print_newline) {
    print "\n";
}

