#!/usr/bin/perl

# $Id$

# This script implements Build-Interceptor LD_PRELOAD mode (see
# doc/modes.txt).
#
# It is the user entry point for LD_PRELOAD mode as well as an intermediate
# script for intercepting child processes.

use strict;
use warnings;
use FindBin;

my $LIB_DIR = "$FindBin::RealBin/lib/build-interceptor";

my $preload_interceptor = "$LIB_DIR/preload_interceptor";

exec {$preload_interceptor} ($preload_interceptor, @ARGV);
